horas= int(input("Horas trabalhadas: "))
valor_hora= int(input("Valor por hora: "))
perc_desc= int(input("Percentual de desconto: "))
dependentes= int(input("Quantidade de dependentes: "))
sal_bruto= (horas*valor_hora)
desconto= (sal_bruto*(perc_desc/100))
sal_liq= (sal_bruto-desconto)
(sal_liq+(dependentes*100))
print("Valor liquido: ", sal_liq)